out_dir: results
metric_best: auc
wandb:
  use: True
  project: moltox
dataset:
  format: OGB
  name: ogbg-moltox21
  task: graph  
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+NodeCentrality 
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_NodeCentrality:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 18
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: colour_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  num_samples: 2
  subgraph_pooling: sum
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 10
  layers_post_mp: 3
  dim_inner: 300
  layer_type: gineconv
  act: gelu
  residual: True
  dropout: 0.3
  batchnorm: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0001
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
